export const ROLE_SEARCH = "ROLE_SEARCH";
export const ROLE_UPDATE = "ROLE_UPDATE";
export const ROLE_CREATE = "ROLE_CREATE";
export const ROLE_DELETE = "ROLE_DELETE";
export const ROLE_GETALL = "ROLE_GETALL";
export const ROLE_FIND_BY_NAME = "ROLE_FIND_BY_NAME";

export const USER_SEARCH = "USER_SEARCH";
export const USER_UPDATE = "USER_UPDATE";
export const USER_CREATE = "USER_CREATE";
export const USER_DELETE = "USER_DELETE";
export const USER_FIND_BY_NAME = "USER_FIND_BY_NAME";
export const USER_GET_ROLENAME_ALL = "USER_GET_ROLENAME_ALL";
export const USER_GET_CLAIMNAME_ALL = "USER_GET_CLAIMNAME_ALL";
