// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RcrsCore.IdentityServer.Models;

namespace RcrsCore.IdentityServer.Data.Migrations.City
{
    [DbContext(typeof(CityDbContext))]
    partial class CityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("RcrsCore.IdentityServer.Models.DomainEntity.M_市区町村", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("メモ")
                        .HasColumnType("TEXT");

                    b.Property<string>("住所")
                        .HasColumnType("TEXT");

                    b.Property<string>("市区町村CD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(6);

                    b.Property<string>("市区町村名")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("郵便番号")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("都道府県CD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("都道府県名")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("M_市区町村");
                });

            modelBuilder.Entity("RcrsCore.IdentityServer.Models.DomainEntity.M_都道府県", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("都道府県CD")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<string>("都道府県名")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("M_都道府県");
                });
#pragma warning restore 612, 618
        }
    }
}
